export enum deployNetwork {
  bsc_testnet = "bsc_testnet",
  bsc_mainnet = "bsc_mainnet",
  polygon_testnet = "polygon_testnet",
  polygon_mainnet = "polygon_mainnet",
  eth_testnet = "eth_testnet",
  eth_mainnet = "eth_mainnet",
  hardhat = "hardhat",
  localhost = "localhost",
  arbitrum_testnet = "arbitrum_testnet",
  arbitrum_mainnet = "arbitrum_mainnet",
  zksync_era_testnet = "zksync_era_testnet",
  zksync_era_mainnet = "zksync_era_mainnet",
  polygon_zkevm_testnet = "polygon_zkevm_testnet",
  polygon_zkevm_mainnet = "polygon_zkevm_mainnet",
  zk_scroll_testnet = "zk_scroll_testnet",
  zk_scroll_mainnet = "zk_scroll_mainnet",
}
